### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by Michaelspitzbart** [microsoft/vscode-github-issue-notebooks#105]
Hi
i downloaded VSCode with WSL2 and Ubuntu20.4 For the installation i took this tutorial https://docs.microsoft.com/en-us/windows/wsl/install-win10 
After that i opened ubunto and tried to update and it didnt work i get a failare code like this 
![image](https://user-images.githubusercontent.com/72939120/133883749-70f29e9a-7e60-4687-ad44-e9bbd2df7df9.png)

What is the problem with the connection 

Thank you for your support

**Comment by jrieken** [comment]
This isn't the repo to file issues about WSL
