### ISSUE TITLE
Support GitHub label logical OR syntax

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-github-issue-notebooks#106]
now you can do:

```
label:iteration-plan,endgame-plan
```

however, this gives you a ton of syntax errors:
![image](https://user-images.githubusercontent.com/2644648/134961990-f50ee69f-e9b3-46c9-9fc5-6a8455505e50.png)

Running it does actually work, which is nice, but we should recognize that this is an official syntax.

**Comment by bpasero** [comment]
Is this broken? Here is a cell I have:

```
repo:microsoft/vscode is:open no:assignee label:workbench-actions,workbench-cli,workbench-diagnostics,workbench-dnd,workbench-editor-grid,workbench-editor-groups,workbench-editor-resolver,workbench-editors,workbench-electron,workbench-feedback,workbench-history,workbench-hot-exit,workbench-hover,workbench-launch,workbench-link,workbench-multiroot,workbench-notifications,workbench-os-integration,workbench-rapid-render,workbench-run-as-admin,workbench-state,workbench-status,workbench-tabs,workbench-touchbar,workbench-untitled-editors,workbench-views,workbench-welcome,workbench-window,workbench-zen -milestone:"Backlog Candidates"
```

And it returns 1 issue for me:

![image](https://user-images.githubusercontent.com/900690/161297208-b794c331-d1fe-45e5-a62d-f7be35e55241.png)

While in GH itself 88 are returned:

https://github.com/microsoft/vscode/issues?q=repo%3Amicrosoft%2Fvscode+is%3Aopen+no%3Aassignee+label%3Aworkbench-actions%2Cworkbench-cli%2Cworkbench-diagnostics%2Cworkbench-dnd%2Cworkbench-editor-grid%2Cworkbench-editor-groups%2Cworkbench-editor-resolver%2Cworkbench-editors%2Cworkbench-electron%2Cworkbench-feedback%2Cworkbench-history%2Cworkbench-hot-exit%2Cworkbench-hover%2Cworkbench-launch%2Cworkbench-link%2Cworkbench-multiroot%2Cworkbench-notifications%2Cworkbench-os-integration%2Cworkbench-rapid-render%2Cworkbench-run-as-admin%2Cworkbench-state%2Cworkbench-status%2Cworkbench-tabs%2Cworkbench-touchbar%2Cworkbench-untitled-editors%2Cworkbench-views%2Cworkbench-welcome%2Cworkbench-window%2Cworkbench-zen+-milestone%3A%22Backlog+Candidates%22

**Comment by jrieken** [comment]
@bpasero Can you press the home 🏠 icon? It will open the query as it has been parsed and might reveal some inconsistencies. Tho, I have also seen the API and homepage differ is cases and don't know why...

**Comment by bpasero** [comment]
@jrieken oh nice, so there is something going on, the input of the cell is:

```
repo:microsoft/vscode is:open no:assignee label:workbench-actions,workbench-cli,workbench-diagnostics,workbench-dnd,workbench-editor-grid,workbench-editor-groups,workbench-editor-resolver,workbench-editors,workbench-electron,workbench-feedback,workbench-history,workbench-hot-exit,workbench-hover,workbench-launch,workbench-link,workbench-multiroot,workbench-notifications,workbench-os-integration,workbench-rapid-render,workbench-run-as-admin,workbench-state,workbench-status,workbench-tabs,workbench-touchbar,workbench-untitled-editors,workbench-views,workbench-welcome,workbench-window,workbench-zen -milestone:"Backlog Candidates"
```

and the result on GH is:

```
repo:microsoft/vscode is:open no:assignee label:workbench-actions,workbench-cli,workbench-diagnostics,workbench-dnd,workbench-editor-grid,workbench-editor-groups,workbench-editor-resolver,workbench-editors,workbench-electron,workbench-feedback,workbench-history,workbench-hot-exit,workbench-hover,workbench-launch,workbench-link,workbench-multiroot,workbench-notifications,workbench-os-integration,workbench-rapid-render,workbench-run-as-admin,workbench-state,workbench-status,workbench-tabs,workbench-touchbar,workbench-untitled-editors,workbench-views,workbench-welcome,workbench-window,"workbench-zen-milestone:\"Backlog" Candidates" 
```

Notice the extra `"` right before `workbench-zen...`, something going on with parsing?

**Comment by bpasero** [comment]
I am able to resolve this by simply moving the `-milestone:"Backlog Candidates"` to the beginning, so it is related to that.
