### ISSUE TITLE
Empty notebook should show a cell to start typing code?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-github-issue-notebooks#109]
I find an entirely empty notebook not very welcoming to type some code, maybe we should show a code cell by default always?

![image](https://user-images.githubusercontent.com/900690/120273641-127a4380-c2af-11eb-925d-1c863985e930.png)

**Comment by jrieken** [comment]
It actually does that now

<img width="1034" alt="Screen Shot 2021-11-17 at 10 23 28" src="https://user-images.githubusercontent.com/1794099/142173128-56ac465f-d82b-4023-8563-203423a31391.png">
