### ISSUE TITLE
GitHub issues notebook: showing 200 of 162

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-github-issue-notebooks#11]
![image](https://user-images.githubusercontent.com/172399/78332981-511c4d00-7589-11ea-8c39-2830594b413e.png)

**Comment by jrieken** [comment]
@egamma Do you still have that query?

**Comment by jrieken** [comment]
Nevermind, seeing this with OR-queries, like this `repo:microsoft/vscode label:notebook is:open OR repo:microsoft/vscode-github-issue-notebooks is:open`
