### ISSUE TITLE
Latest version of GitHub Issues Notebook extension requires API proposal that is not available in latest VS Code stable

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-github-issue-notebooks#121]
I believe the vscode.engine needs to be updated. cc @kartikm123 for details

**Comment by KartikM123** [comment]
Browser: Chrome/Edge/Firefox
Version of extension: v0.0.116 (latest)

### Steps to reproduce
Whenever I load the latest version of the extension in a github.dev session, I get this error: 
![image](https://user-images.githubusercontent.com/19193984/161122462-5e113417-810f-413a-9ec7-2975938215d3.png).

When I rollback to an older version (eg v0.0.113), the error disappears. I'm not sure if it's related to the API issue we have open: https://github.com/github/codespaces/issues/7229.

---
Let me know if I can provide any more info! The change breaks the extension. I get this error when I try opening a new issue notebook (looks like an API issue)
![image](https://user-images.githubusercontent.com/19193984/161125275-4eb7bff8-1ea8-45d0-a089-59d943655f34.png)

**Comment by jrieken** [comment]
Needs version 0.0.116 and latest insiders
