### ISSUE TITLE
Localize parser strings

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-github-issue-notebooks#135]
> I tried to localize the parser strings as well... but that failed the tests because the unit tests don't have a vscode implementation. Any idea on how I could mock that?

I would keep the parser free of vscode-dependencies. It's a bit of duplication but the [LanguageValidation](https://github.com/microsoft/vscode-github-issue-notebooks/blob/2d5282dc56f0b4db77041a8c1de4cf9491d138d8/src/extension/languageProvider.ts#L679)-strategy could have a mapping from `ValidationError#code` to human-readable messages which are then externalized/translated

_Originally posted by @jrieken in https://github.com/microsoft/vscode-github-issue-notebooks/issues/132#issuecomment-1255907372_

**Comment by hediet** [comment]
What is the bug?

**Comment by joyceerhl** [comment]
Does not seem localized with pseudolang or Japanese, maybe I'm doing this wrong?: 
<img width="637" alt="image" src="https://user-images.githubusercontent.com/30305945/198372557-80401aa6-1efb-448a-b3dc-662c9aa6128b.png">

**Comment by jrieken** [comment]
Hm... In source it is externalized @TylerLeonhardt Is there anything else I need to do? Is this fallback to english or why isn't pseudo lang being used?

<img width="1295" alt="Screenshot 2022-10-28 at 08 55 35" src="https://user-images.githubusercontent.com/1794099/198523042-f07a9d95-5274-426f-b893-cf2c86cee4a9.png">

**Comment by TylerLeonhardt** [comment]
new release out

**Comment by joyceerhl** [comment]
:rocket: <img width="640" alt="image" src="https://user-images.githubusercontent.com/30305945/199302814-d375263b-1737-48f7-a5be-e36a67543902.png">
