### ISSUE TITLE
multiple -assiginee should be allowed

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-github-issue-notebooks#16]
Issue Type: <b>Bug</b>

```
$REDMOND= -assignee:alexdima -assignee:weinand -assignee:alexr00 -assignee:egamma -assignee:aeschli -assignee:isidorn -assignee:chrmarti -assignee:dbaeumer -assignee:bpasero -assignee:sandy081 -assignee:jrieken
```

I'm seeing warnings for `-assignee`, however it's valid as I'm using `-` here.

Extension version: 0.0.10
VS Code version: Code - Insiders 1.45.0-insider (2225d77536d12fea2eda04930f431a5eb0930bba, 2020-04-09T09:26:30.083Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.29GB free)|
|Process Argv|-psn_0_21345370|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rebornix** [comment]
<img width="1489" alt="image" src="https://user-images.githubusercontent.com/876920/78949090-627cc200-7a7f-11ea-870e-2e711c013511.png">

**Comment by jrieken** [comment]
* go to https://github.com/issues
* search for `-assignee:alexdima -assignee:weinand -assignee:alexr00`
* only the last assignee-term remains

**Comment by jrieken** [comment]
<img width="633" alt="Screenshot 2020-04-14 at 10 16 01" src="https://user-images.githubusercontent.com/1794099/79201880-02986980-7e39-11ea-974a-efbc756bd011.png">

**Comment by rebornix** [comment]
@jrieken it looks a UI/.com bug as multiple `-assignee`  actually works pretty good through API and I use that to filter issues by redmond/zurich team.

**Comment by jrieken** [comment]
unsure, try this link `https://github.com/issues?q=repo%3Amicrosoft%2Fvscode+is%3Aissue+is%3Aopen+label%3Asuggest+-assignee%3Ajrieken+-assignee%3Aoctref` but there is a difference if search within the repo's issue page

**Comment by jrieken** [comment]
nope - also within the repo's page it doesn't seem to work. try this: `https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+label%3Asuggest+-assignee%3Ajrieken+-assignee%3Aoctref`

**Comment by jrieken** [comment]
This is soo bizarre - in the web UI this doesn't work, in the extension it. Tho, it doesn't work for milestone in neither. Hard to draw a conclusion, I will tweak this case by case
