### ISSUE TITLE
Notebook never finishes executing

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-github-issue-notebooks#165]
1. Run all in https://insiders.vscode.dev/github/microsoft/vscode/blob/74eb687ea8280d0fc90135e803793944a74fa1b7/.vscode/notebooks/my-endgame.github-issues
2. :bug: this cell never completes https://insiders.vscode.dev/github/microsoft/vscode/blob/main/.vscode/notebooks/my-endgame.github-issues#C34:L1

**Comment by jrieken** [comment]
Works for me... Anything in the logs? Did you get rate limited by any chance?
