### ISSUE TITLE
GH Issues Notebook: Backlog

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-github-issue-notebooks#17]
# Functionality
- [x] code cells support the GH query syntax
- [x] support macros
   - definition: `$BUG= "label:bug"`
   - usage: `repo:microsoft/vscode is:issue ${BUG} notebook`
- [x] support for `OR` such as `(label:bug OR label:important)`
- Language features
   - [x] :runner:  intellisense: keywords; macros, potentially repos, labels, users, milestones
   - [x] syntax check
   - [x] semantic check such as `!label:bug label:bug` and undefined macros
   - [x] go to definition and find all references for macros
   - [x] rename for macros
   - [ ] outline for full notebook
- results
   - [x] text: only list of issue urls
   - [ ] json
   - [x] list of issues (like GH)
- extensions
   - copy result list
   - sort results in various ways
   - define list of repos and have a drop down that lets you switch the default repo
   - [x] mark cells as locked/unlocked (like macOS System Preferences)
- we can grow this over time to allow cells to contain graph QL queries to be polyglot

# Goals for March
- [x] create new notebook: if the NB is empty, provide an empty cell, allow to change cell type/language id
- [x] add cell
- [x] delete cell
- [x] reorder cells (using commands and UI)
- language features
   - [x] syntax highighting
   - [x] semantic highlights
   - [x] syntax check
   - [x] keyword intellisense
   - [x] simple macro support
   - [x] Go to definition of macros
   - [x] Find all references of macros
   - [x] Rename of macros
   - [x] Completions
   - [x] Structured Selection
- [x] Run query
- [x] Render output (low bar: title, owner, milestone)
- [x] Clear output
- [x] Save notebook
- [ ] :hand: Cross cell undo/redo
- [x] notebook meta-data
   - [x] `readonly`: whether or not cells can not be deleted or added
   - [x] `cell-readonly`: default for whether or not cells are read-only
- [x] cell meta-data
   - [x] `readonly`: cell can be modified
   - [x] `runnable`: has a run button
- [x] progress / cancellation
   - [ ] elapsed time

# April
- [ ] Stabilization: performance, grammar, LS
- [ ] Adopt progress being made on notebooks in general (see https://github.com/microsoft/vscode/issues/91987)
- [ ] Outline
- [ ] Provide global indication of `not signed in` and an action to trigger sign-in (not in the window status bar)
- [ ] :muscle: Extension: define list of repos and have a drop down that lets you switch the default repo
- [ ] :muscle: support basic graph QL code-cell (and execution)

**Comment by jrieken** [comment]
Closing this in favour of the list of issues in this repo
