### ISSUE TITLE
"Start working..." shows in the wrong repo

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-github-issue-notebooks#20]
Issue Type: <b>Bug</b>

Currently "Start working..." always shows even if the repo is different from the one on the workspace.

Extension version: 0.0.10
VS Code version: Code - Insiders 1.45.0-insider (b83339a3a7bd8e3ec8a8b79deda9c37e0d91f094, 2020-04-21T05:38:43.781Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.62GB free)|
|Process Argv|-psn_0_13003878|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jrieken** [comment]
For now "start working..." is gone
