### ISSUE TITLE
"Showing" label should reflect current number of rendered results

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-github-issue-notebooks#22]
Issue Type: <b>Bug</b>

testing https://github.com/microsoft/vscode/issues/96279

1. Create GitHub issue notebook
2. Execute a code cell with `repo:microsoft/vscode`

<img width="1273" alt="Screen Shot 2020-04-28 at 4 54 13 PM" src="https://user-images.githubusercontent.com/3672607/80549135-44fd9280-8971-11ea-8cfe-fa24066bf818.png">

The text at the bottom of the output below show more reads "947420 results (showing 1000)". Since it's right by the show more button, I expected this to be indicating how many results were currently rendered

VS Code version: Code - Insiders 1.45.0-insider (abb4a35cfc26102f93fd00df7b59ce1a19c2017a, 2020-04-28T05:34:21.109Z)
OS version: Darwin x64 18.7.0

**Comment by jrieken** [comment]
Yeah, that "showing..." label doesn't make much sense now that I think about it. It only shows when having more result than GH would return. And that's always 1000. We have now also moved the message into the (offical) cell status bar. 


<img width="448" alt="Screenshot 2020-04-29 at 15 29 56" src="https://user-images.githubusercontent.com/1794099/80601577-4b057900-8a2e-11ea-986c-128ab954ddc7.png">

My plan is

1. Don't show the "showing 1000" label anymore
1. Change the "Show More" to "Show N More", e.g "Show 9 More"

**Comment by jrieken** [comment]
This is how it now looks

<img width="545" alt="Screenshot 2020-04-29 at 15 41 46" src="https://user-images.githubusercontent.com/1794099/80602861-f19e4980-8a2f-11ea-9476-6149e6462e58.png">
