### ISSUE TITLE
LS does not "see" cells that are folded

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-github-issue-notebooks#27]
Issue Type: <b>Bug</b>

1) create a cell that defines a variable and fold it away
2) use the variable in another cell
3) close the file/editor
4) reopen the file
-> cell created in step 2 shows error squiggles 

Extension version: 0.0.22
VS Code version: Code - Insiders 1.46.0-insider (e88b8d32aa7233f6cb3665f6dae9fa78b1e8aafb, 2020-05-13T08:04:25.590Z)
OS version: Darwin x64 18.7.0

**Comment by jrieken** [comment]
this is @rebornix (gh is pita and I cannot assign anyone anymore...)

**Comment by jrieken** [comment]
LIke #28 - an issue with the core/API which has been fixed
