### ISSUE TITLE
LS does not "see" cells that have never materialized

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-github-issue-notebooks#28]
Issue Type: <b>Bug</b>

1) create a cell that defines a variable and fold it away
2) create one or more markdown cells so that they are higher than your window size
3) below that create a cell tha uses the variable
4) scroll the editor to the top
5) open the problems view
6) close the file/editor
7) reopen the file -> problem view is empty
8) scroll to the bottom of the notebook -> problems view shows the error 

Although these steps use the bug described in https://github.com/microsoft/vscode-github-issue-notebooks/issues/27 to reproduce the problem, the problem is real :-) 

Extension version: 0.0.22
VS Code version: Code - Insiders 1.46.0-insider (e88b8d32aa7233f6cb3665f6dae9fa78b1e8aafb, 2020-05-13T08:04:25.590Z)
OS version: Darwin x64 18.7.0

**Comment by jrieken** [comment]
this is @rebornix

**Comment by jrieken** [comment]
This was an issue inside the core which has been fixed
