### ISSUE TITLE
Bad diagnostics on my milestone query

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-github-issue-notebooks#35]
Testing: https://github.com/microsoft/vscode/issues/98821

I used intellisense to auto complete the milestone part:

![image](https://user-images.githubusercontent.com/2193314/83550232-60514580-a4bb-11ea-95a8-b3be719ba3c0.png)

**Comment by Tyriar** [comment]
There are also 2, maybe they should be merged into a single error?

![image](https://user-images.githubusercontent.com/2193314/83551776-a909fe00-a4bd-11ea-916e-97368349f219.png)

**Comment by jrieken** [comment]
Quotes are needed
