### ISSUE TITLE
Milestone filters incorrectly

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-github-issue-notebooks#4]
Issue Type: <b>Bug</b>

`repo:microsoft/vscode label:notebook is:open -milestone:"April 2020" -milestone:"Backlog"` doesn't filter out issues assigned to `Backlog` milestone.

Extension version: 0.0.3
VS Code version: Code - Insiders 1.44.0-insider (20b88fa0694cae8e46ffd305a1450ba58ae6065b, 2020-04-01T08:34:11.087Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.81GB free)|
|Process Argv|-psn_0_4691065|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jrieken** [comment]
@rebornix So, there is one problem with the name, it is Backlog without quotes. But, still when pasting this query here `https://github.com/issues` then only the last milestone filter is effective, e.g after the reload the first milestone is removed from the query...

**Comment by jrieken** [comment]
It looks like the last one wins for the web and that it's the other way around for us...

**Comment by jrieken** [comment]
Ok, only now realised that those are negated. This should be fixed now (after N attempts...)
