### ISSUE TITLE
GH notebooks: "start working" frantic UI

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-github-issue-notebooks#46]
Currently we render the "start working" after the labels.
This gives a bit of a frantic feeling when I hover over multiple rows, since it is always in a different place. I usually quite dislike this UI, and prefer when the location is stable, since this gives a more calming effect.
Thus I suggest we allign the "start working" to the right. Left of the assignee

Bonus issue: if I do not give permission to the GH PR extension, additional clicks on it have no effect. It should always prompt me to give permision.

![Screenshot 2020-06-10 at 22 21 41](https://user-images.githubusercontent.com/1926584/84314696-c64b6600-ab68-11ea-8f58-9213329df244.png)

**Comment by jrieken** [comment]
It's gone for now
