### ISSUE TITLE
Support Python in the notebook

### ISSUE THREAD

**Issue by harrism** [microsoft/vscode-github-issue-notebooks#48]
Great potential in this extension. I'd love to be able to use it to build an interactive dashboard notebook. To that end, being able to use Python (or other language) in cells to manipulate query results would be amazing. If I could get the results of a query in an array and use that to generate statistics so I can feed them into visualizations, for instance. Even getting the size of the array would be useful. Then I could track changes in the number of issues open under a certain label over time, etc.

Better documentation would be nice, too. Right now it's unclear what is the difference between queries with "or", "and", and without either (e.g. between labels).  

Thanks!

**Comment by jrieken** [comment]
>  If I could get the results of a query in an array and use that to generate statistics so I can feed them into visualizations, for instance. 

Glad you are asking ;-) The notebook "kernel" actually already does that. When executing a cell it will produce outputs of three types: text/html, text/markdown, and x-application/github-issues. The latter is what you want, its format is the JSON results as they come from the servers. 

<img width="773" alt="Screenshot 2020-06-17 at 14 45 02" src="https://user-images.githubusercontent.com/1794099/84899579-22524500-b0a9-11ea-89e9-8d5f0702fe02.png">

Your request plays nice into the notebooks design as have defined the concept of [`NotebookOutputRenderer`](https://github.com/microsoft/vscode/blob/ca7f2683fda363d848b3bb12b0b2b8f0fa4fd158/src/vs/vscode.proposed.d.ts#L1537). Think about it as a transformer that can take cell output, like x-application/github-issues, and turn it into a pretty html. We have some (unpolished) samples here: https://github.com/microsoft/notebook-extension-samples. For instance a regexper-output-renderer: https://github.com/microsoft/notebook-extension-samples/blob/a7cce65bb94f865542cc54628a478ec284240c56/notebook-regexper/src/extension.ts#L58

**Comment by harrism** [comment]
Sorry, I don't understand why you closed this. I see no way to  run code other than the queries in the cells of the notebooks provided by this extension.
