### ISSUE TITLE
Allow OR syntax on variables

### ISSUE THREAD

**Issue by harrism** [microsoft/vscode-github-issue-notebooks#49]
Example, suppose I have these variables:

```
$cudf=repo:rapidsai/cudf
$cuio_issues = is:issue is:open label:cuIO
$libcudf_issues = is:issue is:open label:libcudf -label:cuIO
```

It would be nice if this worked (it doesn't appear to):

```
$cudf $cuio_issues OR $cudf $libcudf_issues
```

Instead I have to write it all out (this works):

```
$cudf is:issue is:open label:cuIO OR $cudf is:issue is:open label:libcudf -label:cuIO
```

It would also be nice if this worked:

```
$query1 = $cudf $cudf_issues
$query2 = $cudf $cuio_issues
$query1 OR $query2
```

**Comment by jrieken** [comment]
I believe the issue with your queries is the space character after the equals sign. Todays parser isn't very forgiving here. Can you try without those spaces, it then works for me


<img width="756" alt="Screenshot 2020-06-17 at 15 10 54" src="https://user-images.githubusercontent.com/1794099/84902176-beca1680-b0ac-11ea-9219-36143e6a0680.png">

**Comment by harrism** [comment]
Good to hear it works. Seems like a simple fix to make the parser more flexible? Feel free to use this as an issue for that or close.

**Comment by babakks** [comment]
I'd like to help on this @jrieken.

**Comment by jrieken** [comment]
Cool. This is where parsing happens: https://github.com/microsoft/vscode-github-issue-notebooks/blob/8cfb2ad5048807ba11d27348f4639a9d99d6fc91/src/parser/parser.ts#L357, this is where tests are https://github.com/microsoft/vscode-github-issue-notebooks/blob/8cfb2ad5048807ba11d27348f4639a9d99d6fc91/src/test-unit/parser.test.ts#L11. Run them with `npm run unit-test`

**Comment by babakks** [comment]
@jrieken I've made the PR #59.
