### ISSUE TITLE
repo completions do not suggest all vscode repositories

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-github-issue-notebooks#5]
<img width="506" alt="image" src="https://user-images.githubusercontent.com/172399/78257437-1c14e980-74fa-11ea-9062-ee1e8051a356.png">

**Comment by jrieken** [comment]
So, turns that the endpoint also need pagination. Problem is that the MSTF org 3152 repos and that fetching them takes forever...

<img width="753" alt="Screenshot 2020-04-03 at 17 29 10" src="https://user-images.githubusercontent.com/1794099/78377991-a465be00-75d0-11ea-80dc-3d7c2dea7ef6.png">

**Comment by jrieken** [comment]
https://developer.github.com/v3/search/#search-repositories might

**Comment by jrieken** [comment]
There is now two paths

1. fetch repos that you own
2. search for repos by given prefix

Unfortunately 2 makes this a little slowing...
