### ISSUE TITLE
Availability of this extension in production release

### ISSUE THREAD

**Issue by liny01-nbsa** [microsoft/vscode-github-issue-notebooks#51]
I have tried to search but, couldn't find definitive information on this:

Is this extension currently available in prod release of vscode?

It shows in the latest release note.

![image](https://user-images.githubusercontent.com/38985073/85162540-8b63c500-b22f-11ea-8db3-ec0048ed6898.png)

But then the extension says it only works in insider version:

![image](https://user-images.githubusercontent.com/38985073/85162616-a7676680-b22f-11ea-8bcd-beda7df57ad6.png)

If that's the case any I can do in prod release to make it work?

Thanks!

**Comment by jrieken** [comment]
At the moment this is only for insiders: https://code.visualstudio.com/insiders. We will make this generally available as soon as notebooks are.

**Comment by liny01-nbsa** [comment]
Thank you, @jrieken.
