### ISSUE TITLE
Locked cells and undo/redo

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode-github-issue-notebooks#52]
Issue Type: <b>Bug</b>

Testing https://github.com/microsoft/vscode/issues/98991

1. Create github-issues notebook with two cells
2. Type in a cell, then lock it

Try to undo, nothing happens. So my expectation is then that locked cells will not respond to undo. 

3. Type in the other cell
4. Repeatedly undo

I'm able to remove the text from the locked cell.

VS Code version: Code - Insiders 1.46.0-insider (1bfa086adb9271ff56be11821da686e4cfffb672, 2020-06-02T08:10:00.819Z)
OS version: Darwin x64 18.7.0

**Comment by jrieken** [comment]
There is no more locking of cell... We might return with a similar but different concept for read mode for notebooks
