### ISSUE TITLE
Can't assign `sort:reactions-+1-desc` to a variable

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-github-issue-notebooks#54]
For `$upvote_sort=sort:reactions-+1-desc` I get an error of `query expected`:

```json
{
	"resource": "...",
	"owner": "_generated_diagnostic_collection_name_#9",
	"code": "NodeMissing",
	"severity": 8,
	"message": "query expected",
	"startLineNumber": 4,
	"startColumn": 1,
	"endLineNumber": 4,
	"endColumn": 36
}
```

**Comment by JacksonKearl** [comment]
Seeing that while no error is thrown, the sort clause gets silently dropped when included via a variable.
![image](https://user-images.githubusercontent.com/8586769/89585417-a942b480-d7f2-11ea-80cf-843312605b68.png)
![image](https://user-images.githubusercontent.com/8586769/89585463-be1f4800-d7f2-11ea-8246-0159c2a855d5.png)
