### ISSUE TITLE
Using a variable that specifies a sort does not seem to apply that sort

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-github-issue-notebooks#60]
E.g. `$upvotes=sort:reactions-+1-desc` and then using `$upvotes` in a search does not seem to apply the sort. Putting the sort in manually via `sort:reactions-+1-desc` does work.

**Comment by jrieken** [comment]
dupe of https://github.com/microsoft/vscode-github-issue-notebooks/issues/54
