### ISSUE TITLE
Render open/closed with some color

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-github-issue-notebooks#74]
It is currently difficult to distinguish open from closed issues
![image](https://user-images.githubusercontent.com/172399/97000984-e25c0c80-1537-11eb-8137-1e7757e9e5b1.png)

**Comment by jrieken** [comment]
<img width="381" alt="Screenshot 2020-10-29 at 17 27 19" src="https://user-images.githubusercontent.com/1794099/97602790-058d2d00-1a0c-11eb-90d6-df0eebc18db2.png">
