### ISSUE TITLE
Unknown qualifier in markdown text?

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-github-issue-notebooks#75]
This is in the `.vscode/notebooks/grooming-delta.github-issues` notebook

![image](https://user-images.githubusercontent.com/172399/98228735-467bc900-1f59-11eb-9fad-6c6833df33d6.png)

**Comment by jrieken** [comment]
wow... That would mean that the markdown cell somehow makes it into the GH query language service. @egamma do you recall anything special like change cell type, copy pasting cell, undo/redo, or something like that?

**Comment by egamma** [comment]
The problem persists when I close the workspace and open the notebook again.

The cell looks OK to me:

```json
  {
    "kind": 1,
    "language": "markdown",
    "value": "# vscode\n\nQuery exceeds the maximum result. Run the query manually: `is:issue is:open closed:>2020-10-01`",
    "editable": true
  },
```

**Comment by jrieken** [comment]
Yeah, the `kind` and `language` property seem correct.

**Comment by jrieken** [comment]
Actually quite obvious, there is a [place](https://github.com/microsoft/vscode-github-issue-notebooks/blob/3f888d952b8bf3a1931d5e1543522a469f4a38cd/src/extension/project.ts#L150) at which all cell are fed into the language service. Funny that this didn't come up sooner. A believe this makes a good point for a better API separate of code and markdown cells - see https://github.com/microsoft/vscode/issues/105933
