### ISSUE TITLE
misleading milestone syntax error

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-github-issue-notebooks#8]
Issue Type: <b>Bug</b>

Sometimes I get syntax error for milestones but not 100% of the time.

```
repo:microsoft/vscode label:notebook is:open milestone:"April 2020"
```

<img width="1831" alt="image" src="https://user-images.githubusercontent.com/876920/78307863-c3dee700-74fb-11ea-9b6a-698dded5868f.png">

Extension version: 0.0.4
VS Code version: Code - Insiders 1.44.0-insider (d8e3cca049b1baa317ab9ef0d3f673b08e53d8fa, 2020-04-02T06:40:18.155Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by jrieken** [comment]
Not sure how that can happen... I have unit-tests for the validation so suspect that this is something with models not being updated or my validation debouncing not working
