### ISSUE TITLE
Goals - Editing/Viewing Issue Content From Within VSCode 

### ISSUE THREAD

**Issue by danieldjewell** [microsoft/vscode-github-issue-notebooks#84]
One of the things I've noticed about all (? - nearly all?) of the GitHub integration extensions for VSCode is that they seem to always want to launch a browser for anything related to viewing/editing/commenting on an issue. 

For whatever reason (and especially when I'm writing a comment or working on a GH issue), I have extremely bad luck with either hitting the back button, something crashing, or whatever causing all of my typed progress to be (frequently) lost. Because the GH issues web interface does not have an automatic draft saving system (like Outlook/Exchange365/Office365 Word/Gmail), I'm outta luck. 

So, instead, and especially on longer writeups/issues, I like to use VS Code to edit the issue text so I can save it. There are several good extensions (including the built-in markdown support) that allow me to preview the GFM markdown. 

Yet, the one feature that I cannot seem to find is a way to view the issue comments/post a comment directly from VSCode. Instead, I have to open up the browser and copy/paste. While this isn't *horrible*, it sure would be nice to have the ability to directly interact with the contents of an issue from within VSCode. I think this extension could be a great place to do it -- doesn't have to be complex. 

Just a thought 😁

**Comment by jrieken** [comment]
No plans to do that. This notebook is designed to be a trampoline to the browser and not a replacement
