### ISSUE TITLE
Clear cell outputs appears for cells that haven't executed

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-github-issue-notebooks#86]
Testing microsoft/vscode#119715

![image](https://user-images.githubusercontent.com/2193314/112289567-a98da400-8c4b-11eb-8744-d27284ebb84f.png)

**Comment by rebornix** [comment]
It only happens in a few notebooks and I found that GH NB does provide an `NotebookOutput` for the cell but its `items` is an empty array.

**Comment by jrieken** [comment]
Looks like this has been fixed
